/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 */

plugins {
    application
}

repositories {
    mavenCentral()
}

application {
    mainClass.set("main.java.ru.nsu.fit.vinter.lab1.multicastUDP.Main")
}